### ISSUE TITLE
Compile fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by optseb** [stnuessl/rf#2]
Hi, 

I was keen to try rf out for my command line refactoring needs. 

Unfortunately, clang must have changed its API a bit, because I get some compiler errors:

Before pasting in a great load of compiler error messages, I wondered if you know of any other tools like this (perhaps that's why you didn't develop this any further?) or if you have a feel for how complex it is to keep up with clang?

**Comment by stnuessl** [comment]
Hi,

by now there is clang-rename which should fulfill the same job and probably has better integration into text editors or IDEs (and better maintainance ). Keeping up with the API changes of clang-tooling usually isn't too hard if you are willing to commit to it. I would estimate at most 4h per major version upgrade if there is any breakage at all(guessing from experience). One nice thing about rf is, that it uses parallelism to speed up the refactoring across all source files in a project. I'm not sure if other tools also do this and I would be kind of surprised if they did (they might have better single thread performance, though). Let me know if you still want to try out rf and I'll try to get it fixed by the end of this week.

**Comment by optseb** [comment]
Hello, thanks very much for the reply. I'll look into clang-rename - that was the hint I needed I guess. Don't feel the need to update your code on my account - though it looks like you built a nice tool and put a lot of work into documenting it.
